
# SEO settings
title: "Blink Shell Documentation"
title2: "" # default: ""
description: "Blink Shell Documentation"
keywords: "blink shell, documentation"
url: blinksh.github.io # site url
baseurl: "/documentation" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-84834352-1
# repo: http://github.com/heiswayi/thinkspace
# disqus_shortname: ""
# twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
# author:
#   name     : "Heiswayi Nrird"
#   job      : "R&D Software Engineer"
#   bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
#   thumb    : /images/author.jpg
#   email    : hnrird@gmail.com
#   url      : http://heiswayi.github.io
#   github   : http://github.com/heiswayi
#   twitter  : http://twitter.com/HeiswayiNrird
#   facebook : https://www.facebook.com/profile.php?id=1257583160
#   linkedin : http://linkedin.com/in/nrird

# social settings
# og_locale: "en_US"
# twitter_card: "summary_large_image"
# twitter_site: "@HeiswayiNrird"

plugins:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
